### ISSUE TITLE
I get some warnings when did make'

### ISSUE THREAD

**Issue by csanyipal** [pekingduck/emacs-sqlite3-api#1]
Hi,
I did followings:
git clone https://github.com/pekingduck/emacs-sqlite
cd emacs-sqlite3-api/
make
gcc -g3 -Wall -std=c99 -I. -fPIC -c sqlite3-api.c
In file included from sqlite3-api.c:1041:0:
consts.c: In function ‘emacs_module_init’:
consts.c:266:55: warning: passing argument 2 of ‘env->make_integer’ makes integer from pointer without a cast [-Wint-conversion]
 defconst(env, "sqlite-static", env->make_integer(env, SQLITE_STATIC));
                                                       ^~~~~~~~~~~~~
consts.c:266:55: note: expected ‘intmax_t {aka long int}’ but argument is of type ‘void (*)(void *)’
consts.c:267:58: warning: passing argument 2 of ‘env->make_integer’ makes integer from pointer without a cast [-Wint-conversion]
 defconst(env, "sqlite-transient", env->make_integer(env, SQLITE_TRANSIENT));
                                                          ^~~~~~~~~~~~~~~~
consts.c:267:58: note: expected ‘intmax_t {aka long int}’ but argument is of type ‘void (*)(void *)’
gcc -shared -o sqlite3-api.so sqlite3-api.o -lsqlite3
rm sqlite3-api.o

Is this normal?

Best, Pal

**Comment by pekingduck** [comment]
Yes you can safely ignore the warnings (SQLITE_TRANSIENT and SQLITE_STATIC are only relevant
if you use the sqlite3 C api).

Actually I just updated the code so you should not see them anymore :)
