### ISSUE TITLE
Add version & tag

### ISSUE THREAD

**Issue by r0man** [pekingduck/emacs-sqlite3-api#4]
Hello @pekingduck,

I'm packaging this repository for GNU Guix. Could you please help me with this and add a version to this Emacs package and create a Git tag for it? This would allow me to get rid of these warnings when linting this package via `guix lint`.

```
/home/roman/workspace/guix/gnu/packages/emacs-xyz.scm:5741:14: warning: no tags were found for emacs-sqlite3-api
/home/roman/workspace/guix/gnu/packages/emacs-xyz.scm:5741:14: emacs-sqlite3-api@0.0.1-0.88dfeae: updater 'github' failed to find upstream releases
```

Thanks, Roman.

**Comment by pekingduck** [comment]
Hi Roman,

Tag "v0.15" created. 

Regards

**Comment by r0man** [comment]
Thank you!
